version: "3"

services:
  # mysql:
  #   container_name: db
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
  #     - MYSQL_DATABASE=$DB_NAME
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
  #     timeout: 20s
  #     retries: 10

  app:
    container_name: app-docker
    build: .
    environment:
      - PORT=$PORT
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - SECRET_KEY=$SECRET_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
      - AWS_CERTIFICATES_BUCKET_NAME=$AWS_CERTIFICATES_BUCKET_NAME
    ports:
      - "3000:80"