version: "3"

services:
  mysql:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Serve-and-Shine
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    container_name: app-docker
    build: .
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=Serve-and-Shine
      - DB_PORT=3306
    ports:
      - "3000:80"
    depends_on:
      mysql:
        condition: service_healthy
